Add pv and us
sabinadayanova/text-extractor pull request #1
Opened 2021-02-26 10:12 UTC by sabinadayanova

ПР для того, чтобы добавить product vision и user stories

by @sabinadayanova @julykosheleva @darya-baranovskaya

2021-02-26 12:19 UTC, nvamelichev commented
Замечания с семинара:
* Принимаем мнение заказчика, что основные пользователи - это программисты ("люди, знакомые с программированием"), с учётом этого поправить Vision и User Stories
* Написать риски проекта в Vision
* Отранжировать User Stories по важности для основных пользователей. Например, сценарий "извлечь текст из кучи файлов и склеить обратно в PDF/DOCX/DOC/..." явно малоприоритетный и, возможно, стоит его пока убрать. (А потом уже будете реализовывать проект, поймёте больше о пользователях и проекте, и можно будет к этой идее вернуться)
* Убрать сценарий про "базы данных" из User Stories, концентрируемся на текстовых документах (pdf, doc[x], возможно, djvu)

2021-02-26 14:49 UTC, sabinadayanova reviewed
А извлекать текст из картинок не планируется? @nvamelichev

2021-02-26 17:02 UTC, nvamelichev commented
> А извлекать текст из картинок не планируется? @nvamelichev

Эту идею можно оставить "на будущее", вдруг ваш проект быстро полетит и вам скучно станет?

А пока OCR мне кажется излишним. Сейчас лучше сосредоточиться на извлечении данных из пары хорошо известных форматов, например, PDF и DOCX.

2021-02-26 19:04 UTC, nvamelichev requested changes

2021-02-26 19:04 UTC, nvamelichev commented on user_stories.md
> +
напоминаю, что мы ещё хотели историю про программиста, который конвертнул 499 файликов а потом в ту же папку положил 500-й, и не хочет при следующей конвертации все 500 файлов обрабатывать, если новый/изменившийся среди них только один

2021-02-26 23:20 UTC, nvamelichev requested changes
В основном замечания к стилю изложения. Точно собранные и записанные требования = счастливый заказчик и всё такое :-)

2021-02-26 23:20 UTC, nvamelichev commented on product_vision.md
> +программированием и работающие с большим количеством данных.
лучше немного уточнить, что имеется в виду под "работающие с **большим количеством данных**": 
а) с данными (суммарно или индивидуально) большого объёма; б) с большим количеством мелких файлов; в) иное?

2021-02-26 23:20 UTC, nvamelichev commented on product_vision.md
> +С помощью этой программы вы можете сливать содержимое одного или
мелочь: сможете **сливать** -> сможете **объединить**

2021-02-26 23:20 UTC, nvamelichev commented on product_vision.md
> +документов и поиска по ключевым словам. Таким образом, наша
перед "поиска по ключевым словам" лучше указать уточнение "**полнотекстового**"

2021-02-26 23:20 UTC, nvamelichev commented on product_vision.md
> +других дисциплин универстита и сложности при работе с библиотеками
очепятка: универ**стита** -> универ**ситета**

2021-02-26 23:20 UTC, nvamelichev commented on user_stories.md
> +- Как студент, программист и исследователь,  я бы хотел извлекать тексты из pdf/doc/docx/word файлов для
* pdf/doc/docx/word файлов - 3 из 4 это расширения файлов, Word же - программа. Кажется лишним в перечислении, можно просто убрать, оставив: "pdf/doc/docx"
* Нечаянный лишний пробел перед "я бы хотел"

2021-02-26 23:20 UTC, nvamelichev commented on user_stories.md
> +- Как программист, я бы хотел сливать содержимое (возможно похожих по содержанию) файлов различных форматов в один текстовый
сливать -> объединять

2021-02-26 23:20 UTC, nvamelichev commented on user_stories.md
> +  файл, чтобы впоследствии анализировать контент файлов (ключевые слова, гистограммы и т.п.).
согласованность терминов: либо везде "контент", либо везде "содержимое" (я за "содержимое")

2021-02-26 23:20 UTC, nvamelichev commented on user_stories.md
> +- Как программист, я бы хотел иметь возможность регулярно выделять текстовое содержимое файлов
Всю историю, но особенно &mdash; фразу "**хотел иметь возможность регулярно выделять** ... содержимое файлов" **очень** трудно парсить. Потому что [нанизывание падежей (п. 6)](https://meduza.io/cards/kak-izbavit-svoyu-rech-ot-kantselyarita).

Я бы переформулировал как-то так: "Как программист, я бы хотел регулярно извлекать текст только из новых или изменившихся файлов [в папке]".

2021-02-27 19:21 UTC, nvamelichev approved these changes
Looks good to me 👍

2021-02-27 19:24 UTC, merged